### ISSUE TITLE
Unexcepted exit when check ip is enabled

### ISSUE THREAD

**Issue by Gaojianli** [Henryzhao96/bupt_net_login#1]
Sep 14 11:49:15 acc bupt_net_login.sh[2863]: Mon 14 Sep 2020 11:49:15 AM CST - Check interval: 120
Sep 14 11:49:15 acc bupt_net_login.sh[2869]: Mon 14 Sep 2020 11:49:15 AM CST - Current IP: 10.206.15.235
Sep 14 11:49:15 acc bupt_net_login.sh[2844]: /usr/local/bin/bupt_net_login.sh: 59: Bad substitution
Sep 14 11:49:15 acc systemd[1]: bupt_net_login.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

**Comment by HenryzhaoH** [comment]
Archiving repo.
